version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: walletmate-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: walletmate
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: walletmate-backend
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/walletmate?createDatabaseIfNotExist=true
      - DB_USERNAME=root
      - DB_PASSWORD=123456
      - SERVER_PORT=8081
      - JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - JWT_EXPIRATION=86400000
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5501,http://localhost:3000

volumes:
  mysql-data:
