services:
  - type: web
    name: walletmate
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: MYSQL_ROOT_PASSWORD
        sync: false
        value: 123456
      - key: MYSQL_DATABASE
        value: walletmate
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://localhost:3306/walletmate
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
        value: 123456
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 86400000
      - key: ALLOWED_ORIGINS
        value: https://*.onrender.com,http://localhost:5173
    healthCheckPath: /actuator/health
    healthCheckTimeout: 180
    disk:
      name: data
      mountPath: /var/lib/mysql
      sizeGB: 1
