spring.application.name=walletmate

# JWT Configuration
auth.token.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
auth.token.expirationInMs=86400000

# Spring Security Configuration
spring.security.user.name=admin
spring.security.user.password=admin

# Authentication Configuration
spring.security.authentication.token.secret-key=${auth.token.jwtSecret}
spring.security.authentication.token.expiration=${auth.token.expirationInMs}

# Server Configuration
server.port=8081

# DataSource Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Multipart Configuration
spring.servlet.multipart.max-file-size=500KB
spring.servlet.multipart.max-request-size=500KB

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true

# CORS Configuration
app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5501,http://localhost:3000

# Logging Configuration
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.mail=DEBUG
logging.level.rw.financial.walletmate.security.jwt=TRACE
logging.level.rw.financial.walletmate.security=TRACE
logging.level.rw.financial.walletmate.controller=TRACE
logging.level.rw.financial.walletmate.service=TRACE
logging.level.org.springframework.web=TRACE
logging.level.org.springframework.security.authentication=TRACE

# Log to file
logging.file.name=app.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

spring.main.allow-bean-definition-overriding=true